version: "3.8"

services:
  keuanganku:
    image: ${IMAGE_NAME:-your-dockerhub-username/keuanganku:latest}
    pull_policy: always
    container_name: keuanganku
    restart: unless-stopped
    network_mode: "host" # Akses aplikasi langsung di port host 7432
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    logging:
      driver: "none"
